### ISSUE TITLE
Support toggling POJO properties

### ISSUE THREAD

**Issue by poteto** [poteto/ember-toggle-helper#3]

**Comment by miguelcobain** [comment]
Using normal `Ember.set`/`Ember.get` [here](https://github.com/poteto/ember-toggle-helper/blob/master/addon%2Fhelpers%2Ftoggle.js#L7) would handle both the POJO and non-POJO scenarios.

**Comment by poteto** [comment]
Confirm :) I just wanted to get this out quickly. Will update when I'm at a keyboard

**Comment by poteto** [comment]
Or if you have some time to spare, I would be very happy to accept a PR for it!

**Comment by miguelcobain** [comment]
On it.

**Comment by rwjblue** [comment]
The [implementation of toggleProperty](https://github.com/emberjs/ember.js/blob/1a2cd166a86219717a0cde1df4dab497d8dda3e3/packages/ember-runtime/lib/mixins/observable.js#L485-L487):

``` js
  toggleProperty(keyName) {
    return set(this, keyName, !get(this, keyName));
  },
```

**Comment by miguelcobain** [comment]
Too bad `toggleProperty` isn't in the Ember namespace, i.e `Ember.toggleProperty(obj, keyName)`. Not a big deal. :)
